### ISSUE TITLE
Multi GPU strategy

### ISSUE THREAD

**Issue by baniasbaabe** [PacktPublishing/Hands-On-Image-Generation-with-TensorFlow-2.0#8]
Is there are reason why you never used a strategy (like MirrorStrategy, etc.) despite of having 4 GPUs?

**Comment by soon-yau** [comment]
You can see the use of MirrorStrategy in some of the models like VAE (if I remember correctly). The reason that it is not used in GANs is because it is not possible with **custom training step** outside of model. You will get error when you try to do that. 

However, half way writing the book I found out a new Keras feature that allow overriding train step (check out [this page](**custom training step**). I haven't tried it but I believe this will allow the use of mult-gpus.

**Comment by baniasbaabe** [comment]
Oh ok thanks, so I can remove the "train"-method and do the customizations in the "train-step"-method?

**Comment by baniasbaabe** [comment]
Or  is it possible e.g. for the StyleGAN implementation to inherit the class from keras.Model and then make the customizations for the train_step? And leave anything else like how it is?
